// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	categories "main.go/business/categories"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: ctx, domain
func (_m *Repository) CreateCategory(ctx context.Context, domain categories.Domain) (categories.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 categories.Domain
	if rf, ok := ret.Get(0).(func(context.Context, categories.Domain) categories.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(categories.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, categories.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCategoryById provides a mock function with given fields: ctx, id
func (_m *Repository) DeleteCategoryById(ctx context.Context, id int) (categories.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 categories.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) categories.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(categories.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCategory provides a mock function with given fields: ctx
func (_m *Repository) GetAllCategory(ctx context.Context) ([]categories.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []categories.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []categories.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]categories.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategoryById provides a mock function with given fields: ctx, id
func (_m *Repository) GetCategoryById(ctx context.Context, id int) (categories.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 categories.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) categories.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(categories.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
